#!/usr/bin/env bash

export FZF_DEFAULT_OPTS="--height=100% --layout=reverse -i --prompt=\"~ \" --color=dark,hl:red:regular,fg+:white:regular,hl+:red:regular:reverse,query:white:regular,info:gray:regular,prompt:red:bold,pointer:red:bold"

#exec alacritty --class="fzf-menu" -e bash -c "fzf-tmux -m $* < /proc/$$/fd/0 | awk 'BEGIN {ORS=\" \"} {print}' > /proc/$$/fd/1"
# For st instead
# st -c fzf-menu -n fzf-menu -e bash -c "fzf-tmux -m $* < /proc/$$/fd/0 | awk 'BEGIN {ORS=\" \"} {print}' > /proc/$$/fd/1"
# xterm -name 'floating term' -e "fzf $* < /proc/$$/fd/0 > /proc/$$/fd/1"
st -n 'floating-term' -e bash -c "fzf $* < /proc/$$/fd/0 > /proc/$$/fd/1"
