#!/usr/bin/env sh

# https://raw.githubusercontent.com/ThePrimeagen/.dotfiles/master/bin/.local/bin/tmux-sessionizer

set +e

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(echo "$@" | sed 's/ /\n/g' | fzf --reverse)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

# create new session if not exists
tmux has-session -t="${selected_name}" 2> /dev/null || tmux new-session -ds "${selected_name}" -c "${selected}" 2> /dev/null

# script called inside tmux
if [[ ! -z $TMUX ]]; then
  tmux switch-client -t $selected_name
  exit 0
fi

# script called outside tmux
tmux a -t $selected_name
