#!/usr/bin/env sh

# https://raw.githubusercontent.com/ThePrimeagen/.dotfiles/master/bin/.local/bin/tmux-sessionizer

set +e

folder_path="$1"
session_name="$2"

if [ -z "${folder_path}" ]; then
  exit 0
fi

if [ -z "${session_name}" ]; then
  session_name=$(basename "$folder_path" | tr . _)
fi

tmux_running=$(pgrep tmux)

if [ -z "${tmux_running}" ]; then
  tmux new-session -s "$session_name" -c "$folder_path"
  exit 0
fi

# create new session if not exists
tmux has-session -t="${session_name}" 2>/dev/null || tmux new-session -ds "${session_name}" -c "${folder_path}" 2>/dev/null

# script called inside tmux
if [ -n "${TMUX}" ]; then
  tmux switch-client -t "$session_name"
  exit 0
fi

# script called outside tmux
tmux a -t "$session_name"
